version: '3.1'
services:
    web_blue:
        build:
            context: .
            dockerfile: Dockerfile
        image: vedronix_frontend:blue
        container_name: vedronixfrontend-blue
        ports:
            - '5179:5179'
        networks:
            - backend
        restart: always
        
        environment:
            - TZ=Asia/Kolkata
        

networks:
    backend:
        external: true